version: '3.8'

services:
  nextjs:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs
    environment:
      JWT_SECRET: "NE60hAlMyF6wVlOt5+VDKpaU/I6FJ4Oa5df1gpG/MTg="
      NEXT_PUBLIC_API_URL: "" 
    expose:
      - "3000"
    volumes:
      - shared-uploads:/app/uploads
    networks:
      - app-network
    depends_on:
      - fastapi

  fastapi:
    build:
      context: ./ai-backend
      dockerfile: Dockerfile
    container_name: fastapi
    environment:
      MONGODB_URI: "mongodb://host.docker.internal:27017/futureforceai"
      JWT_SECRET: "NE60hAlMyF6wVlOt5+VDKpaU/I6FJ4Oa5df1gpG/MTg="
    expose:
      - "8000"
    volumes:
      - shared-uploads:/app/uploads
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - nextjs
      - fastapi
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  shared-uploads:
