version: '3.8'

services:
  # 1) Next.js container
  nextjs:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs
    environment:
      JWT_SECRET: "NE60hAlMyF6wVlOt5+VDKpaU/I6FJ4Oa5df1gpG/MTg="
      # This tells your Next.js app where to find the API
      # Since you're using Nginx, requests can be relative to the domain
      NEXT_PUBLIC_API_URL: ""  # Empty means use relative URLs
    expose:
      - "3000"
    volumes:
      - shared-uploads:/app/uploads
    networks:
      - app-network
    depends_on:
      - fastapi

  # 2) FastAPI container
  fastapi:
    build:
      context: ./ai-backend
      dockerfile: Dockerfile
    container_name: fastapi
    environment:
      # Add environment variables for your API here
      MONGODB_URI: "mongodb://host.docker.internal:27017/futureforceai"
      JWT_SECRET: "NE60hAlMyF6wVlOt5+VDKpaU/I6FJ4Oa5df1gpG/MTg="
    expose:
      - "8000"
    volumes:
      - shared-uploads:/app/uploads
    networks:
      - app-network

  # 3) Nginx reverse proxy
  nginx:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - nextjs
      - fastapi
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  shared-uploads:
    # Named volume for shared uploads between containers